GET http://localhost:6000/products/addProduct

###

GET http://localhost:6000/products

###


GET http://localhost:6000/products/single

###

POST http://localhost:6000/products
Content-Type: application/json

{
    
}

###

DElETE http://localhost:6000/products/2

###

PUT http://localhost:6000/products/2
Content-Type: application/json

{
    
}

###