//Products

GET http://localhost:6000/products

###

GET http://localhost:6000/products/607ece4f341fdf1a52bb05e0

###

POST http://localhost:6000/products
Content-Type: application/json

{   
    "title": "Stickad tröja",
    "price": 599
}

###

DElETE http://localhost:6000/products/607ee134af3095295858846c

###

PUT http://localhost:6000/products/607ede27c2801d27e87977b2
Content-Type: application/json

{
    "title": "grön tröja",
    "price": 888
}

###

//Users

GET http://localhost:6000/users/loggedIn

###

GET http://localhost:6000/users/loggedIn/role

###

POST http://localhost:6000/users/register
Content-Type: application/json

{
    "userName": "erik Svensson",
    "password": "123456",
}

###

POST http://localhost:6000/users/login
Content-Type: application/json

{
    "userName": "Erik Svensson",
    "password": "123456"
}

###

DELETE http://localhost:6000/users/logout

###

GET http://localhost:6000/users/allUsers

###