//Posts

GET http://localhost:6000/api/posts/

###

GET http://localhost:6000/api/posts/

###

POST http://localhost:6000/api/posts/
Content-Type: application/json

{   
    "post": "Har nån hört något om Github?"
}

###

DElETE http://localhost:6000/api/posts/607ee134af3095295858846c

###

PUT http://localhost:6000/api/posts/607ede27c2801d27e87977b2
Content-Type: application/json

{
    "post": "Nu finns min bok att köpa"
}

###

//Users

GET http://localhost:6000/api/users/loggedIn

###

GET http://localhost:6000/api/users/loggedIn/role

###

POST http://localhost:6000/api/users/register
Content-Type: application/json

{
    "userName": "erik Svensson",
    "password": "123456"
}

###

POST http://localhost:6000/api/users/login
Content-Type: application/json

{
    "userName": "Erik Svensson",
    "password": "123456"
}

###

DELETE http://localhost:6000/api/users/logout

###

GET http://localhost:6000/api/users/allUsers

###